### ISSUE TITLE
Cannot run RDF2Any as deamon

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/RDF2Any#4]
As it is, the RDF2Any cannot run as deamon in the background.
In order to fix this I've replaced the main function in the file /linda/src/main/java/com/servlet/Main.java:
```
public static void main(String[] args) throws IOException, InterruptedException {
        final HttpServer server = startServer();
        System.out.println(String.format("Jersey app started with WADL available at "
                + "%sapplication.wadl\nHit Ctrl+C to stop\n", BASE_URI));
		/*Remove reading from stdin to allow running as deamon*/
        while (true) { //don't wait for user input -- just do somenting else -- you could wait for a signal to stop
                Thread.sleep(10);
        }
    }
```
Please make sure the solution is acceptable!

**Comment by gsingharoy** [comment]
This solution is okay, but then it will by default always run a daemon. This can be difficult for a developer as he won't see log messages. Maybe it will be a good idea to specify with an argument say '-d' to run in daemon mode. Otherwise it will run in the default development mode.

**Comment by dipapaspyros** [comment]
The developer is still able to see log messages in the standard output. When running as a deamon (nohup mvn:exec ...) the output can easily be redirected to a log file (by default nohup.out).
If you think it's necessary, you're welcome to seperate the two workflows via a flag. However, i would suggest not to expect user input (no service does anyway, and RDF2Any *is* a service), and to catch the ctlr+c signal generated by the OS to run any clean-up code.
